### ISSUE TITLE
Request users/1 doesn't work

### ISSUE THREAD

**Issue by mohlek** [katharsis-project/katharsis-examples#20]
I am having trouble requesting http://some.url/api/users/1
It always produces 
```
12:17:31,164 ERROR [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-5) RESTEASY002010: Failed to execute: javax.ws.rs.NotFoundException: RESTEASY003210: Could not find resource for full path: http://127.0.0.1:8080/DDGRestAPI/users/1
```

Related to the documentation it should be possible to do so.
http://katharsis.io/docs#supported-requests

I build a example project based on the wildfly-example project and can't get it to work.
Have I done something wrong? https://github.com/mohlek/RestAPI
 
Any help would be great.

**Comment by mohlek** [comment]
noone? :cry:

**Comment by ieugen** [comment]
I don't have experience with wildfly but it seems you've missed a configuration somewhere. Add some brakepoints to see if your requests reach katharsis. They do not seem to get there. Try to see if the feature registration is done properly.

**Comment by mohlek** [comment]
Omg .. I literally read the source 100x times.
There is no problem with my source neither the lib. My assumption was just different. I excepted the endpoint to return null/empty data when there is no data. Instead it throws an error and returns 501 which is in my opinion NOT the way to go but nvm ...
```
.orElseThrow(() -> new ResourceNotFoundException("users/" + id));
```

So sry for being foolish :smile:
